[tools]
python = "3.14.8"
kubectl = "1.37.1"
fnox = "1.36.0"
terraform = "1.16.4"
starship = "1.26.0"
zoxide = "0.10.0"
gitui = "0.28.1"
task = "3.54.0"
tmux = "3.7c"
"go:github.com/hay-kot/scaffold" = "0.13.1"
"cargo:yazi-fm" = "25.5.31"
"cargo:yazi-cli" = "25.5.31"
"aqua:neovim/neovim" = "0.12.5"
go = "1.27.1"
"go:golang.org/x/tools/gopls" = "0.23.0"
delta = "0.19.2"
"aqua:junegunn/fzf" = "0.74.4"
"aqua:koalaman/shellcheck" = "0.11.0"
"cargo:ast-grep" = "0.45.3"
"cargo:tlrc" = "1.13.1"
"cargo:tree-sitter-cli" = "0.27.0"
bat = "0.26.1"
fd = "10.5.0"
ripgrep = "15.2.0"
jq = "1.8.2"
yq = "4.54.1"
gh = "2.102.0"
kubectx = "0.11.0"
helm = "4.3.0"
direnv = "2.37.1"
uv = "0.12.22"
"github:natecraddock/zf"= { version = "0.10.2", bin = "zf" }
"cargo:raine/workmux" = { version = "tag:v0.1.212" }
elixir = "1.20.4"
erlang = "29.1"
node = "26.10.0"
"npm:@mermaid-js/mermaid-cli" = "12.0.0"

"pipx:git-machete" = "3.46.0"
"github:hpcsc/mutants" = { version = "0.3.1", prerelease = true }

[settings]
experimental = true
minimum_release_age_excludes = ["github:hpcsc/mutants"]
