[tools]
python = "3.14.2"
kubectl = "1.36.3"
terraform = "1.15.8"
starship = "1.26.0"
zoxide = "0.10.0"
gitui = "0.28.1"
task = "3.52.0"
"go:github.com/hay-kot/scaffold" = "0.11.0"
"cargo:yazi-fm" = "25.5.31"
"cargo:yazi-cli" = "25.5.31"
neovim = "0.12.4"
go = "1.26.6"
"go:golang.org/x/tools/gopls" = "0.23.0"
delta = "0.19.2"
"aqua:junegunn/fzf" = "0.74.2"
"cargo:ast-grep" = "0.45.1"
"cargo:tlrc" = "1.13.1"
tree-sitter = "0.26.12"
bat = "0.26.1"
fd = "10.4.2"
ripgrep = "15.2.0"
jq = "1.8.2"
yq = "4.53.3"
gh = "2.83.2"
kubectx = "0.11.0"
helm = "4.2.4"
direnv = "2.37.1"
uv = "0.12.5"
"github:natecraddock/zf"= { version = "0.10.2", bin = "zf" }
"cargo:raine/workmux" = { version = "tag:v0.1.212" }
elixir = "1.20.2"
erlang = "29.0"
node = "24.19.0"
"npm:@mermaid-js/mermaid-cli" = "11.16.0"

"pipx:git-machete" = "3.44.1"

[settings]
experimental = true
