version: '3'

output: group
set: [pipefail]

includes:
  common:
    taskfile: ./Taskfile_common.yml
  macos:
    taskfile: ./Taskfile_darwin.yml
  ubuntu:
    taskfile: ./Taskfile_ubuntu.yml
  fedora:
    taskfile: ./Taskfile_fedora.yml

env:
  LOG_DIR: ./logs

tasks:
  default:
    desc: Full installation
    interactive: true
    cmds:
      - |
          if [ "${DRY_RUN:-0}" != "1" ]; then
            mkdir -vp "${LOG_DIR}/$(date +%Y%m%d-%H%M%S)"
            FLAGS=
          else
            FLAGS='-s'
          fi
          if [[ "$(uname -s)" == "Darwin" ]]; then
            task ${FLAGS} default-macos
          elif grep -q 'Ubuntu' /etc/os-release 2>/dev/null; then
            task ${FLAGS} default-ubuntu
          elif grep -q 'Fedora' /etc/os-release 2>/dev/null; then
            task ${FLAGS} default-fedora
          else
            echo "Unsupported operating system"
            exit 1
          fi

  default-macos:
    desc: macOS full installation
    cmds:
      - task: macos:base
      - task: common:base
      - task: common:core
      - task: common:devtools
      - task: common:langtools
      - task: macos:settings

  default-ubuntu:
    desc: Ubuntu full installation
    cmds:
      - task: ubuntu:base
      - task: common:base
      - task: common:core
      - task: common:devtools
      - task: common:langtools
      - task: ubuntu:extras

  default-fedora:
    desc: Fedora full installation
    cmds:
      - task: fedora:base
      - task: common:base
      - task: common:core
      - task: common:devtools
      - task: common:langtools
      - task: fedora:extras

  up:
    desc: Main entry - run core then prompt for optional
    cmds:
      - task: default
      # - bash install-optional.sh

  dry-run:
    desc: Show what would be executed without running scripts
    silent: true
    cmds:
      - DRY_RUN=1 task -s default
      - echo ""
      - echo "=== Dry run complete. Use 'task default' to execute ==="

  optional:net-core:
    desc: Install .NET Core (Ubuntu only)
    cmds:
      - task: ubuntu:net-core

  optional:krew:
    desc: Install Krew plugins - requires kubectl from common:devtools
    cmds:
      - task: common:krew

  optional:istio:
    desc: Install Istio - requires working-folders from common:base
    cmds:
      - task: common:istio

  status:
    desc: Show installation progress and status
    interactive: true
    cmds:
      - bash ./scripts/_status.sh

  status-quick:
    desc: Quick status summary (one line)
    silent: true
    cmds:
      - bash ./scripts/_status-quick.sh
