"""Tests for commit message steering hook."""

from unittest.mock import patch

from steering.commit_message import (
    build_steering_message,
    check_ai_mention,
    check_capitalization,
    check_co_authored_by,
    check_imperative_mood,
    check_subject_length,
    check_trailing_period,
    handle,
    validate_commit_message,
)


class TestCheckSubjectLength:
    def test_short_subject_passes(self):
        assert check_subject_length("Add auth endpoint", "") is None

    def test_exactly_50_chars_passes(self):
        subject = "A" * 50
        assert check_subject_length(subject, "") is None

    def test_51_chars_fails(self):
        subject = "A" * 51
        result = check_subject_length(subject, "")
        assert "51 chars" in result

    def test_long_subject_reports_length(self):
        subject = "Updated the entire authentication system with new features and more"
        result = check_subject_length(subject, "")
        assert str(len(subject)) in result


class TestCheckAiMention:
    def test_clean_message_passes(self):
        assert check_ai_mention("Fix bug", "Fix bug\n\nDetails here") is None

    def test_claude_in_body_fails(self):
        result = check_ai_mention("", "Generated by Claude")
        assert "Claude" in result

    def test_anthropic_in_body_fails(self):
        result = check_ai_mention("", "Thanks to Anthropic")
        assert result is not None

    def test_case_insensitive(self):
        result = check_ai_mention("", "generated by CLAUDE")
        assert result is not None

    def test_llm_mention_fails(self):
        result = check_ai_mention("", "Used LLM for this")
        assert result is not None


class TestCheckCoAuthoredBy:
    def test_clean_message_passes(self):
        assert check_co_authored_by("", "Fix bug\n\nSigned-off-by: Dev") is None

    def test_co_authored_by_fails(self):
        result = check_co_authored_by("", "Fix bug\n\nCo-Authored-By: Claude")
        assert "Co-Authored-By" in result

    def test_case_insensitive(self):
        result = check_co_authored_by("", "co-authored-by: someone")
        assert result is not None


class TestCheckImperativeMood:
    def test_imperative_passes(self):
        assert check_imperative_mood("Add new feature", "") is None
        assert check_imperative_mood("Fix broken test", "") is None
        assert check_imperative_mood("Refactor auth module", "") is None

    def test_past_tense_fails(self):
        assert "Added" in check_imperative_mood("Added new feature", "")
        assert "Fixed" in check_imperative_mood("Fixed broken test", "")
        assert "Updated" in check_imperative_mood("Updated config", "")
        assert "Implemented" in check_imperative_mood("Implemented feature", "")

    def test_suggests_imperative_form(self):
        result = check_imperative_mood("Added new feature", "")
        assert '"Add"' in result

    def test_non_matching_verb_passes(self):
        assert check_imperative_mood("Bump version", "") is None
        assert check_imperative_mood("Release v1.0", "") is None


class TestCheckTrailingPeriod:
    def test_no_period_passes(self):
        assert check_trailing_period("Add feature", "") is None

    def test_trailing_period_fails(self):
        result = check_trailing_period("Add feature.", "")
        assert "period" in result

    def test_period_mid_sentence_passes(self):
        assert check_trailing_period("Fix v1.2 compat issue", "") is None


class TestCheckCapitalization:
    def test_capitalized_passes(self):
        assert check_capitalization("Add feature", "") is None

    def test_lowercase_fails(self):
        result = check_capitalization("add feature", "")
        assert "lowercase" in result

    def test_empty_subject_passes(self):
        assert check_capitalization("", "") is None


class TestValidateCommitMessage:
    def test_clean_message_returns_no_violations(self):
        assert validate_commit_message("Add auth endpoint") == []

    def test_multiple_violations_all_reported(self):
        msg = "added a very long commit message that exceeds the fifty character limit."
        violations = validate_commit_message(msg)
        assert len(violations) >= 3  # length, past tense (if Added), period, lowercase

    def test_single_violation(self):
        violations = validate_commit_message("add feature")
        assert len(violations) == 1
        assert "lowercase" in violations[0]


class TestHandle:
    def test_non_bash_tool_passes_through(self):
        assert handle({"tool_name": "Read"}) == {}

    def test_non_commit_command_passes_through(self):
        assert handle({
            "tool_name": "Bash",
            "tool_input": {"command": "go test ./..."},
            "tool_response": {"exit_code": 0},
        }) == {}

    def test_failed_commit_passes_through(self):
        assert handle({
            "tool_name": "Bash",
            "tool_input": {"command": "git commit -m test"},
            "tool_response": {"exit_code": 1},
        }) == {}

    @patch("steering.commit_message.get_last_commit_message")
    def test_clean_commit_passes_through(self, mock_get):
        mock_get.return_value = "Add user authentication"
        result = handle({
            "tool_name": "Bash",
            "tool_input": {"command": "git commit -m 'Add user authentication'"},
            "tool_response": {"exit_code": 0},
            "cwd": "/tmp",
        })
        assert result == {}

    @patch("steering.commit_message.get_last_commit_message")
    def test_bad_commit_injects_context(self, mock_get):
        mock_get.return_value = "added stuff."
        result = handle({
            "tool_name": "Bash",
            "tool_input": {"command": "git commit -m 'added stuff.'"},
            "tool_response": {"exit_code": 0},
            "cwd": "/tmp",
        })
        ctx = result["additionalContext"]
        assert "VIOLATION" in ctx
        assert "lowercase" in ctx
        assert "period" in ctx

    @patch("steering.commit_message.get_last_commit_message")
    def test_no_commit_message_passes_through(self, mock_get):
        mock_get.return_value = None
        result = handle({
            "tool_name": "Bash",
            "tool_input": {"command": "git commit -m test"},
            "tool_response": {"exit_code": 0},
            "cwd": "/tmp",
        })
        assert result == {}


class TestBuildSteeringMessage:
    def test_includes_violations(self):
        msg = build_steering_message("Fix bug", ["too long", "bad mood"])
        assert "too long" in msg
        assert "bad mood" in msg

    def test_includes_subject(self):
        msg = build_steering_message("Fix bug", ["issue"])
        assert "Fix bug" in msg

    def test_includes_amend_instruction(self):
        msg = build_steering_message("Fix bug", ["issue"])
        assert "git commit --amend" in msg
