#!/usr/bin/env bash
# Generate the per-tool SKILL.md files from the shared method body plus its seams.
#
# A procedure the agent must follow in full is concatenated, not referenced: splitting
# it into "now read these six files" adds six reads and invites partial compliance,
# which is the failure class this whole arrangement exists to remove. Guidelines are
# the opposite — consulted on demand, read partially by design — and stay referenced.
#
# The `model:` line is deliberately absent from every seam: agent-models.json owns it
# for both trees at once, and two writers for one field means whichever ran last wins.
# Run scripts/gen-agent-models.sh after this one — `task common:gen` does both in order.
#
# Usage: scripts/gen-skills.sh [--check]
#   --check  exit 1 if any generated file is out of date, changing nothing

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
METHOD="$ROOT/link/common/dot-config/.config/ai/method"
RENDER="$ROOT/link/common/dot-local/bin/clerk_method.py"

CHECK=false
[ "${1:-}" = "--check" ] && CHECK=true

# source-dir (under $METHOD)  tool  output-path
TARGETS="
audit-implement claude   $ROOT/link/common/claude/.claude/skills/audit-implement/SKILL.md
audit-implement opencode $ROOT/link/common/dot-config/.config/opencode/skills/audit-implement/SKILL.md
implement claude   $ROOT/link/common/claude/.claude/skills/implement/SKILL.md
implement opencode $ROOT/link/common/dot-config/.config/opencode/skills/implement/SKILL.md
agents/decompose-to-tasks claude   $ROOT/link/common/claude/.claude/agents/decompose-to-tasks.md
agents/decompose-to-tasks opencode $ROOT/link/common/dot-config/.config/opencode/agents/decompose-to-tasks.md
agents/commit claude   $ROOT/link/common/claude/.claude/agents/commit.md
agents/commit opencode $ROOT/link/common/dot-config/.config/opencode/agents/commit.md
agents/run-verifier claude   $ROOT/link/common/claude/.claude/agents/run-verifier.md
agents/run-verifier opencode $ROOT/link/common/dot-config/.config/opencode/agents/run-verifier.md
agents/decompose-to-deliverables claude   $ROOT/link/common/claude/.claude/agents/decompose-to-deliverables.md
agents/decompose-to-deliverables opencode $ROOT/link/common/dot-config/.config/opencode/agents/decompose-to-deliverables.md
"

fail=0

# The generated file is the one a person opens — an agent definition sits in the tree the
# harness reads, while its source sits three directories away under a name nothing points
# at. Say where it came from, in the file itself, or the next edit lands on the copy and
# is reverted by the following generation. Goes after the frontmatter, which has to stay
# the first thing in the file, and is part of the rendered output so --check compares it.
stamp_header() {
  awk -v src="$1" '
    NR == 1 && $0 == "---" { print; fm = 1; next }
    fm == 1 && $0 == "---" {
      print
      printf "<!-- Generated from %s by scripts/gen-skills.sh. Do not edit this file - edit the source and run `task common:gen`. -->\n", src
      fm = 2
      next
    }
    { print }
    END { if (fm != 2) { printf("gen-skills: no frontmatter to stamp in %s\n", src) > "/dev/stderr"; exit 3 } }
  '
}

render() {
  local method=$1 tool=$2 body="$METHOD/$1/body.md" seams="$METHOD/$1/seams/$2"
  [ -f "$body" ]  || { printf 'gen-skills: missing body %s\n' "$body" >&2; return 1; }
  [ -d "$seams" ] || { printf 'gen-skills: missing seams %s\n' "$seams" >&2; return 1; }

  # Every {{seam:name}} becomes seams/<tool>/<name>.md, every {{include:path}} the file
  # under the method root, {{quote:path}} the same as a block quote, and {{var}} a value
  # from the seam directory's vars.tsv. The resolver is clerk's own: the step files under
  # implement/steps/ are read here for the whole document and by `clerk step` one at a
  # time, and one resolver is what keeps the two readings the same. It exits 3 naming an
  # unresolved marker rather than leaving a silent hole.
  python3 "$RENDER" "$METHOD" "$seams" "$body" | stamp_header "${body#$ROOT/}"
}

printf '%s\n' "$TARGETS" | while read -r method tool out; do
  [ -n "$method" ] || continue
  rendered=$(render "$method" "$tool") || { fail=1; continue; }

  if [ "$CHECK" = true ]; then
    # The `model:` line is stamped afterwards by gen-agent-models, from the registry that
    # owns it for both trees. Comparing it here would fail every generated agent for
    # carrying a field this script deliberately does not write.
    if [ ! -f "$out" ] || ! printf '%s\n' "$rendered" | diff -q - <(grep -v '^model: ' "$out") >/dev/null 2>&1; then
      printf 'out of date: %s\n' "${out#$ROOT/}" >&2
      exit 1
    fi
    printf 'up to date:  %s\n' "${out#$ROOT/}"
  else
    mkdir -p "$(dirname "$out")"
    printf '%s\n' "$rendered" > "$out"
    printf 'wrote %s (%s lines)\n' "${out#$ROOT/}" "$(printf '%s\n' "$rendered" | wc -l | tr -d ' ')"
  fi
done
